AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: helo-lambda-functions-urls
      Handler: helo-lambda-functions-urls
      Runtime: go1.x
      AutoPublishAlias: live
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
            AllowOrigins:
                - "https://example.com"
Outputs:
  Function:
    Value: !GetAtt Function.Arn
  FunctionUrlEndpoint:
    Value:
      Fn::GetAtt: FunctionUrl.FunctionUrl
